# Generated by Django 5.2.7 on 2026-01-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_adminprompt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='clinician_consent',
            field=models.BooleanField(default=False),
        ),
    ]
